version: '3.8'
services:
  ollama:
    image: ollama/ollama:0.6.5
    ports:
      - "11434:11434"
  milvus:
    image: milvusdb/milvus:v2.3.15
    ports:
      - "19530:19530"
      - "9091:9091"
    volumes:
      - milvus-data:/var/lib/milvus
  backend: