version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest  # Use the Ollama Docker image (replace with the correct tag)
    container_name: ollama-server
    ports:
      - "5000:5000"  # Exposing port 5000 for Ollama server
    networks:
      - ollama-network

  app:
    build:
      context: ./app  # Path to your application directory containing the Dockerfile
    container_name: app-container
    environment:
      - OLLAMA_API_URL=http://ollama:5000  # Point to Ollama server container
    depends_on:
      - ollama  # Ensure Ollama is started before the app
    networks:
      - ollama-network

networks:
  ollama-network:
    driver: bridge
